---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ingress-controller
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress-controller
subjects:
- kind: ServiceAccount
  name: ingress-controller
  namespace: kube-system

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: ingress-controller

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ingress-controller
data:
  traefik.toml: |
    logLevel = "INFO"

    defaultEntryPoints = ["http"]

    [api]

    [kubernetes]
    namespaces = ["default", "kube-system"]

    [entryPoints]
      [entryPoints.http]
      address = ":80"

    [metrics]
      [metrics.prometheus]

    [traefikLog]
      filePath = "/var/log/traefik/server.jsonlog"
      format   = "json"

    [accessLog]
      format = "json"

      [accessLog.fields]
        defaultMode = "drop"
        [accessLog.fields.names]
        "StartUTC" = "keep"
        "StartLocal" = "keep"
        "Duration" = "keep"
        "FrontendName" = "keep"
        "BackendName" = "keep"
        "BackendAddr" = "keep"
        "ClientHost" = "keep"
        "RequestAddr" = "keep"
        "RequestHost" = "keep"
        "RequestPort" = "keep"
        "RequestMethod" = "keep"
        "RequestPath" = "keep"
        "RequestProtocol" = "keep"
        "RequestLine" = "keep"
        "RequestContentSize" = "keep"
        "OriginDuration" = "keep"
        "OriginContentSize" = "keep"
        "OriginStatus" = "keep"
        "RequestCount" = "keep"

        [accessLog.fields.headers]
          defaultMode = "keep"

---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: ingress-controller
  labels:
    k8s-app: ingress-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: ingress-controller
  template:
    metadata:
      labels:
        k8s-app: ingress-controller
    spec:
      serviceAccountName: ingress-controller
      containers:
      - name: ingress-controller
        image: traefik:alpine
        args: [--configfile=/config/traefik.toml]
        ports:
        - name: http
          containerPort: 80
        - name: admin
          containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        configMap:
          name: ingress-controller

---
kind: Service
apiVersion: v1
metadata:
  name: ingress-controller
spec:
  selector:
    k8s-app: ingress-controller
  type: NodePort
  ports:
    - name: http
      port: 80
      nodePort: 32222

---
kind: Service
apiVersion: v1
metadata: {name: traefik}
spec:
  selector: {k8s-app: ingress-controller}
  ports: [port: 8080]
